name: Shell Commands

on: 
  pull_request:
    types: [opened]

jobs:
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Step 1 - Print current directory using Powershell
        run: Get-Location
      - name: Step 2 - Using bash shell in Windows
        run: pwd
        shell: bash

  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Echo a string
        run: echo "Hello World!"
      - name: Step 2 - Multiline script
        run: |
          npm -v
          node -v
      - name: Python Command
        run: |
          import platform
          print(platform.processor())
        shell: python  
